<a href="https://colab.research.google.com/github/cjayjonathan/Introduction-to-NumPy-Creating-Arrays_HamoyeDSI/blob/main/Introduction_to_NumPy_%26_Creating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Convention for importing numpy

import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [2]:
a = np.array(arr)
print(type(a)) #prints <class 'numpy.ndarray'>
print(a.shape) #prints {4} - a is a id array with 4 items
print(a.dtype) #prints int64

# Get the dimension of a with ndim
print(a.ndim) #prints 1


<class 'numpy.ndarray'>
(4,)
int64
1


In [6]:
b = np.array([[1,2,3], [4,5,6]])
print(b) # prints [[1 2 3] [4 5 6]]


[[1 2 3]
 [4 5 6]]


In [8]:
print(b.ndim) #prints 2
b.shape # prints (2,3) - b a 2d array with 2 rows and 3 columns

2


(2, 3)

There are also some inbuilt functions that can be used to initialize numpy which include empty(), zeros(), ones(), full(), random.random()

Intra-operability of Arrays and Scalars.
Vectorisation in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape. This allows for batch arithmetic operations on the arrays by applying the operator elementwise. Similarly, scalars are also propagated element-wise across an array. For arrays with different sizes, it is impossible to perform element-wise operations instead; numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1.

Indexing With Arrays & Using Arrays for Data Processing
The elements in the example arrays above can be accessed by indexing like lists in Python such that:

In [16]:
np.random.random((2,3))

array([[0.04763119, 0.38996527, 0.91600796],
       [0.06183657, 0.59401387, 0.00768669]])

In [19]:
np.zeros((2,3))
np.zeros((2,3))
np.zeros((2,3))
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])
c + d


array([[13., 13., 13.],
       [10., 10., 10.]])

In [13]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [14]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [15]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [20]:
a[0]

6

In [23]:
a[3]


9

In [24]:
# Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing

d[1, 0:2]

array([9., 8.])

In [25]:
e = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])

# Slicing
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [26]:
# Integer Indexing
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [27]:
# Boolean Indexing
e[e>15]

array([16, 17, 18, 19, 20, 21])

Numpy also has inbuilt mathematical functions like sum(), mean(), std(), corrcoef(), min() and others. It interestingly allows for comparing arrays using == to check if two arrays have the same elements,  elements in the first array are greater than or less than those of the second array using  > and  <.

File Input and Output With Arrays
Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. This can also be done with text files with text files using loadtxt() and savetxt().

In [ ]:
# Pandas - So Much More Than A Cute Animal


Introducing Pandas data structures: Series, DataFrames and Index objects.
Pandas is a library  built on Numpy which is used for data manipulation, with other ways of indexing other than integers. Series, DataFrame, and index are the basic data structures in this library.  Series in pandas can be referred to as a one dimensional array with homogenous elements of different types somewhat similar to numpy arrays; however, it can be indexed differently with specified descriptive labels or integers.  

In [28]:
import pandas as pd
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [29]:
# Creating series with a numpy array
days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])
numpy_days = pd.Series(days_list)
print(numpy_days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [31]:
# Using strings as index
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'], index=['a', 'b', 'c'])

# Create series from a dictionary

days1 = ({'a': 'Monday', 'b': 'Tuesday', 'c': 'Wednesday'})

print(days)

a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [32]:
print(days1)

{'a': 'Monday', 'b': 'Tuesday', 'c': 'Wednesday'}


In [34]:
days[0]

'Monday'

'Monday'

In [36]:
days['c']

'Wednesday'

In [35]:
days[1: ]

b      Tuesday
c    Wednesday
dtype: object

A DataFrame can be described as a table (2 dimensions) made up of many series with the same index. It holds data in rows and columns just like a spreadsheet. Series, dictionaries, lists, other dataframes, and numpy arrays can be used to create new ones. 

In [3]:
# Creata a DataFrame from a dictionary
import pandas as pd
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
           'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75]
           }
df = pd.DataFrame(df_dict, index=[2,4,6,8])
print(df)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


In [5]:
df_list = [['Ghana', 'Accra', 1000, 60],
           ['Kenya', 'Nairobi', 8500, 70],
           ['Nigeria', 'Abuja', 35000, 80],
           ['Togo', 'Lome', 12000, 75]]
df1 = pd.DataFrame(df_list, columns=['Country', 'Capital', 'Population', 'Age'],
                   index=[2, 4, 6, 8])
print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra        1000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


at, iat, iloc and loc are accessors used to retrieve data in dataframes. iloc selects values from the rows and columns by using integer index to locate positions, while loc selects rows or columns using labels. at and iat are used to retrieve single values such that at uses the column and row labels and iat uses indices.

In [6]:
# Select the row at index 3
df.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 8, dtype: object

In [7]:
# Select row with index label 6
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [8]:
# Select the capital column
df['Capital']

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [9]:
df.at[6, 'Country']

'Nigeria'

In [10]:
df.iat[2, 0]

'Nigeria'

Finally, Indexes in pandas are immutable arrays with unique elements. They can also be described as ordered sets for retrieving data in a dataframe and collaborating with multiple dataframes.

The important Pandas functionalities: indexing, reindexing, selection, group, drop entities, ranking, sorting, duplicates and indexing by hierarchy.
Summary and descriptive statistics: measure of central tendency, measure of dispersion, skewness and kurtosis, correlation and multicollinearity.
Similar to Numpy, Pandas has some functions that provide descriptive statistics such as the measures of central tendency, dispersion, skewness and kurtosis, correlation and multicollinearity. Some functions are mode(), median(), mean(), sum(), std(), var(), skew(), kurt() and min(). The describe function gives the summary  of the numeric columns in a dataframe displaying count, mean, standard deviation, interquartile range, minimum and maximum values.

In [11]:
df['Population'].sum()

65500

In [12]:
df.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


Population    16375.00
Age              71.25
dtype: float64

In [13]:
df.describe()

Population        Age
count      4.000000   4.000000
mean   16375.000000  71.250000
std    12499.166639   8.539126
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000

The missing data enigma: Importance, types and handling missing data.
Often, data used for analysis in real life scenarios is incomplete as a result of omission, faulty devices, and many other factors. Pandas represent missing values as NA or NaN which can be filled, removed, and detected with functions like fillna(), dropna(), isnull(), notnull(), replace().

In [16]:
import numpy as np
df_dict2 = {'Name': ['James', 'Yemen', 'Caro', np.nan],
            'Profession': ['Researcher', 'Artist', 'Doctor', 'Writer'],
            'Experience': [12, np.nan, 10, 8],
            'Height': [np.nan, 175, 180, 150]}

new_df = pd.DataFrame(df_dict2)
print(new_df)

    Name  Profession  Experience  Height
0  James  Researcher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0


In [17]:
# Check for cells with missing values as True
new_df.isnull()

Name  Profession  Experience  Height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [18]:
# Remove rows with missing values
new_df.dropna()

Name Profession  Experience  Height
2  Caro     Doctor        10.0   180.0